version: '3'
services:
  app:
    build: .
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app
  test-container:
    build: ./test-container
    command: /bin/bash
    stdin_open: true
    tty: true